### ISSUE TITLE
Multiple Connections on LocalForward

### ISSUE THREAD

**Issue by marcianobandeira** [pyscripter/Ssh-Pascal#11]
Hello, is it possible to make multiple connections through firedac in the ssh tunnel?

When I create the tunnel via ssh client on windows, this is possible, but when I create using the sample in this repository, it crashes when making a second connection.

Thanks.

**Comment by pyscripter** [comment]
Fixed.  Please check and report back.

**Comment by marcianobandeira** [comment]
working perfectly now, thank you very much

**Comment by pyscripter** [comment]
I wanted to ask whether your FireDAC connections are executed in parallel or sequentially (one after the other)?   I think that parallel execution is not working well and I inclined to go back to sequential execution.

I think that port forwarding is not compatible with parallel handling of connections.

**Comment by marcianobandeira** [comment]
Hello @pyscripter my connections are parallel, during the execution of my system, several threads are performed opening and closing connections, our tests using authentication by user and password, worked perfectly.
