### ISSUE TITLE
The `SshExec` project returns additional line consists of garbled characters compared to putty.

### ISSUE THREAD

**Issue by edwinyzh** [pyscripter/Ssh-Pascal#4]
See attached screenshot, putty is on the left and the `SshExec` sample project (without any modification) is on the right. 
You can see that the `SshExec` project returns additional line consists of garbled characters compared to putty.
Any idea? Thanks!

Client OS: Windows 7
Windows Codepage as returned by chcp: 936
Remote Linux: Centos 6 x86_64 
Ssh-Pascal: The latest.
Compiler: XE4.

![ssh-pascal exec ls result error](https://user-images.githubusercontent.com/541197/118149366-0f283080-b444-11eb-92d0-851873a1827a.png)

**Comment by edwinyzh** [comment]
Was thinking it's because the `output` and `ErrOutput` were not initialized, so added the initialization code as following, but the issue remains...
`  Output := ''; ErrOutput := '';`

**Comment by edwinyzh** [comment]
Update 2: Tested another Ubuntu 20.04 with the same result.

**Comment by pyscripter** [comment]
Are you using 32 or 64 bits.   I have seen something similar, but only in 32 bits.

**Comment by edwinyzh** [comment]
Oh that's strange, but definitely a useful clue for further investigation. My Delphi program is **32-bit**.

**Comment by pyscripter** [comment]
It would be nice if we could trace the source of this issue.

**Comment by edwinyzh** [comment]
I'll definitely report back the details if I have tracked down any.

**Comment by virgoparna** [comment]
Bug is in ReadStringFromChannel.
    if Cancelled^ then
    begin
      Buf^ := #0;
      MemoryStream.Write(Buf^, 1);
    end;
This only writes #0 to the end of stream, if Cancelled^ is True. And that means, that if it was not cancelled, then #0 is not added and when AnsiToUnicode assigns it to RawByteString, then it will assign until first random #0 in memory (potential acceess violation). 
Just remove the check. Or replace it with if MemoryStream.Size > 0 then, because it is only needed in this  case.

**Comment by pyscripter** [comment]
@virgoparna @edwinyzh Could you please check the fix?

**Comment by edwinyzh** [comment]
Initial test shown that the issue's fixed. Thank you @virgoparna and @pyscripter !

**Comment by virgoparna** [comment]
Replaced my fix with upstream version and everything seems to work.
